name: VCPI
favicon: null
layout_spectrum: 0.01572002936154604
typography_spectrum: 0.30394745292142034
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c62127'
    - '#231f20'
    - '#ffffff'
    - '#ff0000'
    - '#f4795b'
  brandStrength: 0.5
  lightness: 0.44725788733921945
  saturation: 0.875
  rhythmicContrast: 0.02754141390323639
purpose: []
